"""add leave status table

Revision ID: 1cb5522a3ce6
Revises: 105d12ef4f19
Create Date: 2026-06-22 16:52:38.380995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb5522a3ce6'
down_revision: Union[str, Sequence[str], None] = '105d12ef4f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leaves', sa.Column('leave_status_id', sa.Integer(), nullable=True))
    op.add_column('leaves', sa.Column('admin_reason', sa.Text(), nullable=True))
    op.add_column('leaves', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leaves', 'leave_status', ['leave_status_id'], ['id'])
    op.create_foreign_key(None, 'leaves', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'approved_by')
    op.drop_column('leaves', 'admin_reason')
    op.drop_column('leaves', 'leave_status_id')
    op.drop_table('leave_status')
    # ### end Alembic commands ###
