"""add leave balance columns

Revision ID: 543ffe58ee5b
Revises: f354f268cdb5
Create Date: 2026-06-23 11:56:56.241939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543ffe58ee5b'
down_revision: Union[str, Sequence[str], None] = 'f354f268cdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('paid_leave_balance', sa.Integer(), nullable=False, server_default=sa.text('0'))
    )
    op.add_column(
        'users',
        sa.Column('unpaid_leave_count', sa.Integer(), nullable=False, server_default=sa.text('0'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unpaid_leave_count')
    op.drop_column('users', 'paid_leave_balance')
    # ### end Alembic commands ###
