"""add last_leave_credit

Revision ID: cca271111289
Revises: e82a9018d24a
Create Date: 2026-06-23 18:59:05.275377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca271111289'
down_revision: Union[str, Sequence[str], None] = 'e82a9018d24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_leave_credit', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_leave_credit')
    # ### end Alembic commands ###
