"""add leave_type column

Revision ID: e77b9b4fd546
Revises: cca271111289
Create Date: 2026-06-23 19:30:37.111486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77b9b4fd546'
down_revision: Union[str, Sequence[str], None] = 'cca271111289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('leave_type', sa.String(), nullable=True))
    op.drop_column('leaves', 'leave')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('leave', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('leaves', 'leave_type')
    # ### end Alembic commands ###
